### ISSUE TITLE
Will it work with off-the-shelf boards? 

### ISSUE THREAD

**Issue by alfem** [snopf/snopf#2]
I built a similar but more "primitive" device a few weeks ago, and I wonder if your code will work with one of these "DIYMORE" boards:

https://www.instructables.com/id/MicroKeyRing/

I am really bad in soldering, but your software if superior to mine by far, and I would like to give it a try.

**Comment by snopf** [comment]
It should work, probably with some adjustments, with off-the-shelf boards. Somebody at hackaday suggested a digispark board with an ATiny85. The boards don't use a crystal so the software USB-driver had to be adjusted to using the on-chip oscillator, which afaik is working reliable most of the time.

If you want to try it out I could also send you one of the left-over pcb's from my last soldering session!

**Comment by alfem** [comment]
My board (DIYMore Beetle) has got an ATMega32U4, and It can behave as a keyboard/mouse. It  works on every computer (Linux/Windows/Mac) I have tested BUT my work laptop (usb3 ports).  

I'd love to test your board, if no soldering is required. How can I send you my address?

**Comment by snopf** [comment]
Sent you an email!

**Comment by Fazel94** [comment]
> ... a digispark board with an ATiny85...
Could you give a hint on how one can do it?
Can the crystal be attached by something over I/O port?
