### ISSUE TITLE
Is it possible to write with arduino ide

### ISSUE THREAD

**Issue by mrguai** [snopf/snopf#3]
Is it possible to write with arduino ide

**Comment by snopf** [comment]
I don't know why it shouldn't be possible but I have no experience with Arduino and I guess it might be more complicated than using the standard gnu tools. Using AVR studio should be possible without any problems as well.
Do you mean compiling or flashing or both?

**Comment by mrguai** [comment]
> I don't know why it shouldn't be possible but I have no experience with Arduino and I guess it might be more complicated than using the standard gnu tools. Using AVR studio should be possible without any problems as well.
> Do you mean compiling or flashing or both?

I am an arduino enthusiast and have no experience with AVR Studio.
I want to write hex to tiny85. Is it feasible to use ISP?

**Comment by snopf** [comment]
Yes that should be possible.
If you want you can write the bootloader (https://github.com/snopf/snopf_bootloader) first (using ISP) and then you can upload the firmware hex using the firmware uploader python tool.

**Comment by mrguai** [comment]
> Yes that should be possible.
> If you want you can write the bootloader (https://github.com/snopf/snopf_bootloader) first (using ISP) and then you can upload the firmware hex using the firmware uploader python tool.

ok
Your hardware has an external crystal oscillator, tiny85 doesn't seem to need a crystal oscillator, right?

**Comment by snopf** [comment]
You can try without a crystal but you'll have to change the settings in the usb driver.

**Comment by mrguai** [comment]
> You can try without a crystal but you'll have to change the settings in the usb driver.

ok
